server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:8100/camunda
    username: camunda
    password: camunda
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: vpn-service
