server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:8100/vpn_db
    username: camunda
    password: camunda
  jpa:
    hibernate:
      ddl-auto: none  # Обновляем на 'none', так как Flyway будет управлять схемой БД
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true  # Включаем Flyway
    locations: classpath:db/migration  # Указываем папку, где будут храниться SQL миграции
  application:
    name: vpn-service

logging:
  level:
    org.springframework.web: DEBUG  # Логирование для Spring Web
    org.springframework.web.servlet: TRACE  # Логирование HTTP-запросов
    com.vpnservice: DEBUG
    org.hibernate.SQL: DEBUG  # Логгирование SQL-запросов
    org.hibernate.type.descriptor.sql: TRACE  # Логгирование SQL-типов
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
